apiVersion: v2
name: wutong-console
description: Wutong Wutong-console Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 1.0.0
icon: https://www.wutong-paas.com/images/wutonglog.png
home: https://github.com/wutong-paas/wutong
sources:
  - https://github.com/wutong-paas/wutong
